// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByhtSN2KaqGvg79DF29m99TiidWp03PZQ',
    appId: '1:1028909778495:web:96b4866bcbeafa9240da8a',
    messagingSenderId: '1028909778495',
    projectId: 'gemifyy-19419',
    authDomain: 'gemifyy-19419.firebaseapp.com',
    storageBucket: 'gemifyy-19419.appspot.com',
    measurementId: 'G-ZMFQ4Q63V3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPrY1JHIqXo9DzB0r4njkNEWVKZolv2jc',
    appId: '1:1028909778495:android:327e2e871541a26640da8a',
    messagingSenderId: '1028909778495',
    projectId: 'gemifyy-19419',
    storageBucket: 'gemifyy-19419.appspot.com',
  );
}
